apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::188630578400:role/eksctl-eksctl-demo-nodegroup-ng-1-NodeInstanceRole-ARVYT8LXM9D0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::188630578400:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T01:50:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1473"
  uid: a3e6720b-29e6-4aea-9088-18cf135a4108
